library(maftools)
library(readxl)
library(dplyr)
library(xlsx)
library(survival)
library(survminer)


## read maf & clin data
laml.maf = read.delim(file = paste0('./crc_msk_2017/',"data_mutations_extended2.vep.maf"), sep = "\t", header = T)
laml.clin = read_excel(paste0('./clin_data/', "clin.final3.210202.xlsx"), col_names = TRUE)
laml = read.maf(maf = laml.maf, clinicalData = laml.clin)

laml.clin = read_excel(paste0('./clin_data/', "clin.final.210405.xlsx"), col_names = TRUE)
laml.clin$yrs_5 <- ifelse(clin$Overall.Survival..Months. >= 60, "HIGH", "LOW")
clin2 <- clin %>% filter(!Overall.Survival..Months.== "NA")
clin2 <- clin2 %>% filter(!Overall.Survival.Status== "NA")
table(clin2$yrs_5)
length(unique(clin2$Patient.ID))



## make gene data colums
s1 <- laml.maf %>% filter(Hugo_Symbol == "TP53") %>% select(Tumor_Sample_Barcode)
s2 <- laml.maf %>% filter(Hugo_Symbol == "APC") %>% select(Tumor_Sample_Barcode)
s3 <- laml.maf %>% filter(Hugo_Symbol == "KRAS") %>% select(Tumor_Sample_Barcode)
s4 <- laml.maf %>% filter(Hugo_Symbol == "PIK3CA") %>% select(Tumor_Sample_Barcode)
s5 <- laml.maf %>% filter(Hugo_Symbol == "SMAD4") %>% select(Tumor_Sample_Barcode)
s6 <- laml.maf %>% filter(Hugo_Symbol == "FBXW7") %>% select(Tumor_Sample_Barcode)
s7 <- laml.maf %>% filter(Hugo_Symbol == "BRCA2") %>% select(Tumor_Sample_Barcode)
s8 <- laml.maf %>% filter(Hugo_Symbol == "LRP1B") %>% select(Tumor_Sample_Barcode)
s9 <- laml.maf %>% filter(Hugo_Symbol == "BRAF") %>% select(Tumor_Sample_Barcode)
s10 <- laml.maf %>% filter(Hugo_Symbol == "ARID1A") %>% select(Tumor_Sample_Barcode)
s11 <- laml.maf %>% filter(Hugo_Symbol == "TCF7L2") %>% select(Tumor_Sample_Barcode)
s12 <- laml.maf %>% filter(Hugo_Symbol == "SOX9") %>% select(Tumor_Sample_Barcode)
s13 <- laml.maf %>% filter(Hugo_Symbol == "PTPRS") %>% select(Tumor_Sample_Barcode)

s14 <- laml.maf %>% filter(Hugo_Symbol == "PIK3CB") %>% select(Tumor_Sample_Barcode)
s15 <- laml.maf %>% filter(Hugo_Symbol == "TOP2A") %>% select(Tumor_Sample_Barcode)
s16 <- laml.maf %>% filter(Hugo_Symbol == "ZNRF3") %>% select(Tumor_Sample_Barcode)
s17 <- laml.maf %>% filter(Hugo_Symbol == "CEBPZ") %>% select(Tumor_Sample_Barcode)
s18 <- laml.maf %>% filter(Hugo_Symbol == "NTRK1") %>% select(Tumor_Sample_Barcode)
s19 <- laml.maf %>% filter(Hugo_Symbol == "ASXL1") %>% select(Tumor_Sample_Barcode)
s20 <- laml.maf %>% filter(Hugo_Symbol == "POLE") %>% select(Tumor_Sample_Barcode)
s21 <- laml.maf %>% filter(Hugo_Symbol == "PDGFRB") %>% select(Tumor_Sample_Barcode)
s22 <- laml.maf %>% filter(Hugo_Symbol == "EPHB4") %>% select(Tumor_Sample_Barcode)
s23 <- laml.maf %>% filter(Hugo_Symbol == "PTEN") %>% select(Tumor_Sample_Barcode)
s24 <- laml.maf %>% filter(Hugo_Symbol == "BRCA1") %>% select(Tumor_Sample_Barcode)
s25 <- laml.maf %>% filter(Hugo_Symbol == "ROS1") %>% select(Tumor_Sample_Barcode)

s26 <- laml.maf %>% filter(Hugo_Symbol == "RB1") %>% select(Tumor_Sample_Barcode)
s27 <- laml.maf %>% filter(Hugo_Symbol == "CDKN2C") %>% select(Tumor_Sample_Barcode)
s28 <- laml.maf %>% filter(Hugo_Symbol == "CDKN2B") %>% select(Tumor_Sample_Barcode)
s29 <- laml.maf %>% filter(Hugo_Symbol == "CDKN2A") %>% select(Tumor_Sample_Barcode)
s30 <- laml.maf %>% filter(Hugo_Symbol == "CDKN1B") %>% select(Tumor_Sample_Barcode)
s31 <- laml.maf %>% filter(Hugo_Symbol == "CDKN1A") %>% select(Tumor_Sample_Barcode)
s32 <- laml.maf %>% filter(Hugo_Symbol == "CDK6") %>% select(Tumor_Sample_Barcode)
s33 <- laml.maf %>% filter(Hugo_Symbol == "CDK4") %>% select(Tumor_Sample_Barcode)
s34 <- laml.maf %>% filter(Hugo_Symbol == "CCNE1") %>% select(Tumor_Sample_Barcode)
s35 <- laml.maf %>% filter(Hugo_Symbol == "CCND3") %>% select(Tumor_Sample_Barcode)
s36 <- laml.maf %>% filter(Hugo_Symbol == "CCND2") %>% select(Tumor_Sample_Barcode)
s37 <- laml.maf %>% filter(Hugo_Symbol == "CCND1") %>% select(Tumor_Sample_Barcode)


s1 <- unique(s1)
s2 <- unique(s2)
s3 <- unique(s3)
s4 <- unique(s4)
s5 <- unique(s5)
s6 <- unique(s6)
s7 <- unique(s7)
s8 <- unique(s8)
s9 <- unique(s9)
s10 <- unique(s10)
s11 <- unique(s11)
s12 <- unique(s12)
s13 <- unique(s13)

s14 <- unique(s14)
s15 <- unique(s15)
s16 <- unique(s16)
s17 <- unique(s17)
s18 <- unique(s18)
s19 <- unique(s19)
s20 <- unique(s20)
s21 <- unique(s21)
s22 <- unique(s22)
s23 <- unique(s23)
s24 <- unique(s24)
s25 <- unique(s25)

s26 <- unique(s26)
s27 <- unique(s27)
s28 <- unique(s28)
s29 <- unique(s29)
s30 <- unique(s30)
s31 <- unique(s31)
s32 <- unique(s32)
s33 <- unique(s33)
s34 <- unique(s34)
s35 <- unique(s35)
s36 <- unique(s36)
s37 <- unique(s37)


laml.clin$TP53 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s1$Tumor_Sample_Barcode, "1", "0")
laml.clin$APC <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s2$Tumor_Sample_Barcode, "1", "0")
laml.clin$KRAS <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s3$Tumor_Sample_Barcode, "1", "0")
laml.clin$PIK3CA <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s4$Tumor_Sample_Barcode, "1", "0")
laml.clin$SMAD4 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s5$Tumor_Sample_Barcode, "1", "0")
laml.clin$FBXW7 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s6$Tumor_Sample_Barcode, "1", "0")
laml.clin$BRCA2 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s7$Tumor_Sample_Barcode, "1", "0")
laml.clin$LRP1B <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s8$Tumor_Sample_Barcode, "1", "0")
laml.clin$BRAF <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s9$Tumor_Sample_Barcode, "1", "0")
laml.clin$ARID1A <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s10$Tumor_Sample_Barcode, "1", "0")
laml.clin$TCF7L2 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s11$Tumor_Sample_Barcode, "1", "0")
laml.clin$SOX9 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s12$Tumor_Sample_Barcode, "1", "0")
laml.clin$PTPRS <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s13$Tumor_Sample_Barcode, "1", "0")

laml.clin$PIK3CB <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s14$Tumor_Sample_Barcode, "1", "0")
laml.clin$TOP2A <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s15$Tumor_Sample_Barcode, "1", "0")
laml.clin$ZNRF3 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s16$Tumor_Sample_Barcode, "1", "0")
laml.clin$CEBPZ <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s17$Tumor_Sample_Barcode, "1", "0")
laml.clin$NTRK1 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s18$Tumor_Sample_Barcode, "1", "0")
laml.clin$ASXL1 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s19$Tumor_Sample_Barcode, "1", "0")
laml.clin$POLE <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s20$Tumor_Sample_Barcode, "1", "0")
laml.clin$PDGFRB <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s21$Tumor_Sample_Barcode, "1", "0")
laml.clin$EPHB4 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s22$Tumor_Sample_Barcode, "1", "0")
laml.clin$PTEN <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s23$Tumor_Sample_Barcode, "1", "0")
laml.clin$BRCA1 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s24$Tumor_Sample_Barcode, "1", "0")
laml.clin$ROS1 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s25$Tumor_Sample_Barcode, "1", "0")


laml.clin$RB1 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s26$Tumor_Sample_Barcode, "1", "0")
laml.clin$CDKN2C <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s27$Tumor_Sample_Barcode, "1", "0")
laml.clin$CDKN2B <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s28$Tumor_Sample_Barcode, "1", "0")
laml.clin$CDKN2A <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s29$Tumor_Sample_Barcode, "1", "0")
laml.clin$CDKN1B <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s30$Tumor_Sample_Barcode, "1", "0")
laml.clin$CDKN1A <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s31$Tumor_Sample_Barcode, "1", "0")
laml.clin$CDK6 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s32$Tumor_Sample_Barcode, "1", "0")
laml.clin$CDK4 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s33$Tumor_Sample_Barcode, "1", "0")
laml.clin$CCNE1 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s34$Tumor_Sample_Barcode, "1", "0")
laml.clin$CCND3 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s35$Tumor_Sample_Barcode, "1", "0")
laml.clin$CCND2 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s36$Tumor_Sample_Barcode, "1", "0")
laml.clin$CCND1 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% s37$Tumor_Sample_Barcode, "1", "0")


laml.clin$CDKN1AB <- ifelse(laml.clin$CDKN1A == "1" | laml.clin$CDKN1B == "1", "1", "0")
laml.clin$CDKN2ABC <- ifelse(laml.clin$CDKN2A == "1" | laml.clin$CDKN2B == "1" | laml.clin$CDKN2C == "1", "1", "0")
laml.clin$CCND123 <- ifelse(laml.clin$CCND1 == "1" | laml.clin$CCND2 == "1" | laml.clin$CCND3 == "1", "1", "0")
laml.clin$CDK46 <- ifelse(laml.clin$CDK4 == "1" | laml.clin$CDK6 == "1", "1", "0")


library(descr)
CrossTable(laml.clin$yrs_5, laml.clin$CDK46, prop.c = F, prop.r = T, prop.t = F, prop.chisq = F)

table(laml.clin$CCND1)



table(laml.clin$TOP2A)
table(laml.clin$ZNRF3)
table(laml.clin$CEBPZ)
table(laml.clin$NTRK1)
table(laml.clin$ASXL1)
table(laml.clin$POLE)
table(laml.clin$PDGFRB)
table(laml.clin$EPHB4)
table(laml.clin$PTEN)
table(laml.clin$BRCA1)
table(laml.clin$ROS1)

test <- laml.clin %>% filter(PIK3CB == "1") %>% select(Tumor_Sample_Barcode)
length(unique(test))

table(laml.clin$TP53)
table(laml.clin$APC)

##write.xlsx(laml.clin, paste0('./clin_data/', "crc_msk_2017_clinical_data.210201.xlsx"))


## make pathway colums
p1 <- laml.maf %>% filter(Hugo_Symbol == "APC" | Hugo_Symbol == "TCF7L2" | Hugo_Symbol == "RNF43" | Hugo_Symbol == "CTNNB1" | Hugo_Symbol == "AMER1" | Hugo_Symbol == "PTCH1" | Hugo_Symbol == "AXIN1") %>% select(Tumor_Sample_Barcode)
p2 <- laml.maf %>% filter(Hugo_Symbol == "TP53" | Hugo_Symbol == "ATM" | Hugo_Symbol == "BRCA2" | Hugo_Symbol == "ATR" | Hugo_Symbol == "BRCA1" | Hugo_Symbol == "MSH6" | Hugo_Symbol == "STAG2" | Hugo_Symbol == "CHEK2" | Hugo_Symbol == "ERCC2" | Hugo_Symbol == "PPM1D") %>% select(Tumor_Sample_Barcode)
p3 <- laml.maf %>% filter(Hugo_Symbol == "KRAS" | Hugo_Symbol == "BRAF" | Hugo_Symbol == "NRAS" | Hugo_Symbol == "NF1" | Hugo_Symbol == "MAP2K1" | Hugo_Symbol == "HRAS") %>% select(Tumor_Sample_Barcode)

p1 <- unique(p1)
p2 <- unique(p2)
p3 <- unique(p3)

laml.clin$WNT_B <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p1$Tumor_Sample_Barcode, "1", "0")
laml.clin$Genome_Integrity <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p2$Tumor_Sample_Barcode, "1", "0")
laml.clin$mapk_signaling <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p3$Tumor_Sample_Barcode, "1", "0")

table(laml.clin$Tumor_Sample_Barcode %in% p1$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p2$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p3$Tumor_Sample_Barcode)


## make oncogenic pathway colums
p4 <- laml.maf %>% filter(Hugo_Symbol == "KRAS" | Hugo_Symbol == "BRAF" | Hugo_Symbol == "NF1" | Hugo_Symbol == "ROS1" | Hugo_Symbol == "ERBB3" | Hugo_Symbol == "ERBB2" | Hugo_Symbol == "ERBB4" | Hugo_Symbol == "NRAS" | Hugo_Symbol == "ALK" | Hugo_Symbol == "NTRK3" | Hugo_Symbol == "EGFR" | Hugo_Symbol == "RET" | Hugo_Symbol == "FGFR3" | Hugo_Symbol == "MET" | Hugo_Symbol == "PDGFRB" | Hugo_Symbol == "FLT3" | Hugo_Symbol == "PDGFRA" | Hugo_Symbol == "FGFR1" | Hugo_Symbol == "NTRK1" | Hugo_Symbol == "PTPN11" | Hugo_Symbol == "KIT" | Hugo_Symbol == "ABL1" | Hugo_Symbol == "ERRFI1" | Hugo_Symbol == "NTRK2" | Hugo_Symbol == "ARAF" | Hugo_Symbol == "FGFR2" | Hugo_Symbol == "FGFR4" | Hugo_Symbol == "MAP2K1" | Hugo_Symbol == "IGF1R" | Hugo_Symbol == "JAK2" | Hugo_Symbol == "MAP2K" | Hugo_Symbol == "IRS1" | Hugo_Symbol == "CBL" | Hugo_Symbol == "HRAS" | Hugo_Symbol == "INSRR" | Hugo_Symbol == "MAPK1" | Hugo_Symbol == "MAPK3" | Hugo_Symbol == "RAC1" | Hugo_Symbol == "RAF1") %>% select(Tumor_Sample_Barcode)

p5 <- laml.maf %>% filter(Hugo_Symbol == "PIK3CA" | Hugo_Symbol == "PTEN" | Hugo_Symbol == "TSC2" | Hugo_Symbol == "MTOR" | Hugo_Symbol == "PIK3R1" | Hugo_Symbol == "TSC1" | Hugo_Symbol == "RICTOR" | Hugo_Symbol == "AKT1" | Hugo_Symbol == "AKT3" | Hugo_Symbol == "PIK3CB" | Hugo_Symbol == "PIK3R2" | Hugo_Symbol == "AKT2" | Hugo_Symbol == "PPP2R1A" | Hugo_Symbol == "STK11") %>% select(Tumor_Sample_Barcode)

p6 <- laml.maf %>% filter(Hugo_Symbol == "RB1" | Hugo_Symbol == "CCND1" | Hugo_Symbol == "CDKN2A" | Hugo_Symbol == "CDKN2B" | Hugo_Symbol == "CCNE1" | Hugo_Symbol == "CDK6" | Hugo_Symbol == "CDKN1B" | Hugo_Symbol == "CCND2" | Hugo_Symbol == "CCND3" | Hugo_Symbol == "CDK4" | Hugo_Symbol == "CDKN1A" | Hugo_Symbol == "CDKN2C") %>% select(Tumor_Sample_Barcode)

p7 <- laml.maf %>% filter(Hugo_Symbol == "FBXW7" | Hugo_Symbol == "NOTCH4" | Hugo_Symbol == "NOTCH1" | Hugo_Symbol == "CREBBP" | Hugo_Symbol == "NOTCH3" | Hugo_Symbol == "NOTCH2") %>% select(Tumor_Sample_Barcode)

p8 <- laml.maf %>% filter(Hugo_Symbol == "APC" | Hugo_Symbol == "RNF43" | Hugo_Symbol == "TCF7L2" | Hugo_Symbol == "AXIN1" | Hugo_Symbol == "CTNNB1" | Hugo_Symbol == "ZNRF3" | Hugo_Symbol == "RSPO1") %>% select(Tumor_Sample_Barcode)

p9 <- laml.maf %>% filter(Hugo_Symbol == "TP53" | Hugo_Symbol == "ATM" | Hugo_Symbol == "CHEK2" | Hugo_Symbol == "MDM2") %>% select(Tumor_Sample_Barcode)

p10 <- laml.maf %>% filter(Hugo_Symbol == "SMAD4" | Hugo_Symbol == "ACVR2A" | Hugo_Symbol == "SMAD2") %>% select(Tumor_Sample_Barcode)

p11 <- laml.maf %>% filter(Hugo_Symbol == "MYCN" | Hugo_Symbol == "MYC" | Hugo_Symbol == "MAX") %>% select(Tumor_Sample_Barcode)

p12 <- laml.maf %>% filter(Hugo_Symbol == "TEAD2" | Hugo_Symbol == "NF2") %>% select(Tumor_Sample_Barcode)

p13 <- laml.maf %>% filter(Hugo_Symbol == "KEAP1" | Hugo_Symbol == "NFE2L2" | Hugo_Symbol == "CUL3") %>% select(Tumor_Sample_Barcode)

p4 <- unique(p4)
p5 <- unique(p5)
p6 <- unique(p6)
p7 <- unique(p7)
p8 <- unique(p8)
p9 <- unique(p9)
p10 <- unique(p10)
p11 <- unique(p11)
p12 <- unique(p12)
p13 <- unique(p13)


laml.clin$RTK_RAS <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p4$Tumor_Sample_Barcode, "1", "0")
laml.clin$PI3K <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p5$Tumor_Sample_Barcode, "1", "0")
laml.clin$Cell_Cycle <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p6$Tumor_Sample_Barcode, "1", "0")
laml.clin$NOTCH <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p7$Tumor_Sample_Barcode, "1", "0")
laml.clin$WNT <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p8$Tumor_Sample_Barcode, "1", "0")
laml.clin$TP53_Pathway <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p9$Tumor_Sample_Barcode, "1", "0")
laml.clin$TGF_Beta <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p10$Tumor_Sample_Barcode, "1", "0")
laml.clin$MYC <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p11$Tumor_Sample_Barcode, "1", "0")
laml.clin$Hippo <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p12$Tumor_Sample_Barcode, "1", "0")
laml.clin$NRF2 <- ifelse(laml.clin$Tumor_Sample_Barcode %in% p13$Tumor_Sample_Barcode, "1", "0")

table(laml.clin$Tumor_Sample_Barcode %in% p4$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p5$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p6$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p7$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p8$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p9$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p10$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p11$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p12$Tumor_Sample_Barcode)
table(laml.clin$Tumor_Sample_Barcode %in% p13$Tumor_Sample_Barcode)

##save data
##write.xlsx(laml.clin, paste0('./clin_data/', "clin.final.210205.xlsx"))


clin = read_excel(paste0('./clin_data/', "clin_msk_2017_clinical_data.filtered.210201.xlsx"), col_names = TRUE)

##Co-Occurent gene sets
clin$NTRK1_ASXL1 <- ifelse(clin$NTRK1 == "1", ifelse(clin$ASXL1 == "1", "1", "0"), "0")
clin$POLE_ASXL1 <- ifelse(clin$POLE == "1", ifelse(clin$ASXL1 == "1", "1", "0"), "0")
clin$TOP2A_ASXL1 <- ifelse(clin$TOP2A == "1", ifelse(clin$ASXL1 == "1", "1", "0"), "0")
clin$PDGFRB_EPHB4 <- ifelse(clin$PDGFRB == "1", ifelse(clin$EPHB4 == "1", "1", "0"), "0")
clin$TOP2A_NTRK1 <- ifelse(clin$TOP2A == "1", ifelse(clin$NTRK1 == "1", "1", "0"), "0")
clin$TOP2A_POLE <- ifelse(clin$TOP2A == "1", ifelse(clin$POLE == "1", "1", "0"), "0")
clin$ASXL1_FBXW7 <- ifelse(clin$ASXL1 == "1", ifelse(clin$FBXW7 == "1", "1", "0"), "0")
clin$NTRK1_FBXW7 <- ifelse(clin$NTRK1 == "1", ifelse(clin$FBXW7 == "1", "1", "0"), "0")
clin$TOP2A_FBXW7 <- ifelse(clin$TOP2A == "1", ifelse(clin$FBXW7 == "1", "1", "0"), "0")
clin$PTEN_BRCA1 <- ifelse(clin$PTEN == "1", ifelse(clin$BRCA1 == "1", "1", "0"), "0")
clin$ROS1_BRCA1 <- ifelse(clin$ROS1 == "1", ifelse(clin$BRCA1 == "1", "1", "0"), "0")
clin$ASXL1_ARID1A <- ifelse(clin$ASXL1 == "1", ifelse(clin$ARID1A == "1", "1", "0"), "0")
clin$EPHB4_ARID1A <- ifelse(clin$EPHB4 == "1", ifelse(clin$ARID1A == "1", "1", "0"), "0")

##write.xlsx(clin, paste0('./clin_data/', "clin_msk_2017_clinical_data.filtered.210201.xlsx"))

clin = read_excel(paste0('./clin_data/', "clin.final.210201.xlsx"), col_names = TRUE)

s1 <- laml.maf %>% filter(Hugo_Symbol == "MTOR") %>% select(Tumor_Sample_Barcode)
s2 <- laml.maf %>% filter(Hugo_Symbol == "MSH6") %>% select(Tumor_Sample_Barcode)
s3 <- laml.maf %>% filter(Hugo_Symbol == "BRAF") %>% select(Tumor_Sample_Barcode)
s4 <- laml.maf %>% filter(Hugo_Symbol == "BARD1") %>% select(Tumor_Sample_Barcode)
s5 <- laml.maf %>% filter(Hugo_Symbol == "ERBB3") %>% select(Tumor_Sample_Barcode)
s6 <- laml.maf %>% filter(Hugo_Symbol == "NOTCH3") %>% select(Tumor_Sample_Barcode)
s7 <- laml.maf %>% filter(Hugo_Symbol == "MPL") %>% select(Tumor_Sample_Barcode)
s8 <- laml.maf %>% filter(Hugo_Symbol == "ASH1L") %>% select(Tumor_Sample_Barcode)
s9 <- laml.maf %>% filter(Hugo_Symbol == "EZH2") %>% select(Tumor_Sample_Barcode)
s10 <- laml.maf %>% filter(Hugo_Symbol == "AR") %>% select(Tumor_Sample_Barcode)
s11 <- laml.maf %>% filter(Hugo_Symbol == "ETV6") %>% select(Tumor_Sample_Barcode)
s12 <- laml.maf %>% filter(Hugo_Symbol == "SEC63") %>% select(Tumor_Sample_Barcode)
s13 <- laml.maf %>% filter(Hugo_Symbol == "PTCH2") %>% select(Tumor_Sample_Barcode)


s1 <- unique(s1)
s2 <- unique(s2)
s3 <- unique(s3)
s4 <- unique(s4)
s5 <- unique(s5)
s6 <- unique(s6)
s7 <- unique(s7)
s8 <- unique(s8)
s9 <- unique(s9)
s10 <- unique(s10)
s11 <- unique(s11)
s12 <- unique(s12)
s13 <- unique(s13)

clin$MTOR <- ifelse(clin$Tumor_Sample_Barcode %in% s1$Tumor_Sample_Barcode, "1", "0")
clin$MSH6 <- ifelse(clin$Tumor_Sample_Barcode %in% s2$Tumor_Sample_Barcode, "1", "0")
clin$BRAF <- ifelse(clin$Tumor_Sample_Barcode %in% s3$Tumor_Sample_Barcode, "1", "0")
clin$BARD1 <- ifelse(clin$Tumor_Sample_Barcode %in% s4$Tumor_Sample_Barcode, "1", "0")
clin$ERBB3 <- ifelse(clin$Tumor_Sample_Barcode %in% s5$Tumor_Sample_Barcode, "1", "0")
clin$NOTCH3 <- ifelse(clin$Tumor_Sample_Barcode %in% s6$Tumor_Sample_Barcode, "1", "0")
clin$MPL <- ifelse(clin$Tumor_Sample_Barcode %in% s7$Tumor_Sample_Barcode, "1", "0")
clin$ASH1L <- ifelse(clin$Tumor_Sample_Barcode %in% s8$Tumor_Sample_Barcode, "1", "0")
clin$EZH2 <- ifelse(clin$Tumor_Sample_Barcode %in% s9$Tumor_Sample_Barcode, "1", "0")
clin$AR <- ifelse(clin$Tumor_Sample_Barcode %in% s10$Tumor_Sample_Barcode, "1", "0")
clin$ETV6 <- ifelse(clin$Tumor_Sample_Barcode %in% s11$Tumor_Sample_Barcode, "1", "0")
clin$SEC63 <- ifelse(clin$Tumor_Sample_Barcode %in% s12$Tumor_Sample_Barcode, "1", "0")
clin$PTCH2 <- ifelse(clin$Tumor_Sample_Barcode %in% s13$Tumor_Sample_Barcode, "1", "0")

test <- clin %>% filter(MTOR == "1") %>% select(Tumor_Sample_Barcode)
length(unique(test))

table(clin$MTOR)
table(clin$MSH6)

clin$MTOR_MSH6 <- ifelse(clin$MTOR == "1", ifelse(clin$MSH6 == "1", "1", "0"), "0")
clin$BRAF_BARD1 <- ifelse(clin$BRAF == "1", ifelse(clin$BARD1 == "1", "1", "0"), "0")
table(clin$MTOR_MSH6)
table(clin$MTOR, clin$MSH6)

##write.xlsx(clin, paste0('./clin_data/', "clin.final2.210201.xlsx"))


## read maf & clin data
maf = read.delim(file = paste0('./crc_msk_2017/',"data_mutations_extended2.vep.maf"), sep = "\t", header = T)
clin = read_excel(paste0('./clin_data/', "clin.final.210405.xlsx"), col_names = TRUE)

##Gene
s1 <- maf %>% filter(Hugo_Symbol == "PIK3CB") %>% select(Tumor_Sample_Barcode)
s2 <- maf %>% filter(Hugo_Symbol == "TOP2A") %>% select(Tumor_Sample_Barcode)
s3 <- maf %>% filter(Hugo_Symbol == "NTRK1") %>% select(Tumor_Sample_Barcode)
s4 <- maf %>% filter(Hugo_Symbol == "ZNRF3") %>% select(Tumor_Sample_Barcode)
s5 <- maf %>% filter(Hugo_Symbol == "ARID1A") %>% select(Tumor_Sample_Barcode)
s6 <- maf %>% filter(Hugo_Symbol == "ERBB3") %>% select(Tumor_Sample_Barcode)
s7 <- maf %>% filter(Hugo_Symbol == "NOTCH3") %>% select(Tumor_Sample_Barcode)
s8 <- maf %>% filter(Hugo_Symbol == "MSH6") %>% select(Tumor_Sample_Barcode)
s9 <- maf %>% filter(Hugo_Symbol == "PDGFRB") %>% select(Tumor_Sample_Barcode)
s10 <- maf %>% filter(Hugo_Symbol == "EPHB4") %>% select(Tumor_Sample_Barcode)
s11 <- maf %>% filter(Hugo_Symbol == "ASH1L") %>% select(Tumor_Sample_Barcode)
s12 <- maf %>% filter(Hugo_Symbol == "EZH2") %>% select(Tumor_Sample_Barcode)
s13 <- maf %>% filter(Hugo_Symbol == "MTOR") %>% select(Tumor_Sample_Barcode)
s14 <- maf %>% filter(Hugo_Symbol == "AR") %>% select(Tumor_Sample_Barcode)
s15 <- maf %>% filter(Hugo_Symbol == "ETV6") %>% select(Tumor_Sample_Barcode)
s16 <- maf %>% filter(Hugo_Symbol == "SEC63") %>% select(Tumor_Sample_Barcode)
s17 <- maf %>% filter(Hugo_Symbol == "CEBPZ") %>% select(Tumor_Sample_Barcode)
s18 <- maf %>% filter(Hugo_Symbol == "PTCH2") %>% select(Tumor_Sample_Barcode)
s19 <- maf %>% filter(Hugo_Symbol == "BRCA2") %>% select(Tumor_Sample_Barcode)


s1 <- unique(s1)
s2 <- unique(s2)
s3 <- unique(s3)
s4 <- unique(s4)
s5 <- unique(s5)
s6 <- unique(s6)
s7 <- unique(s7)
s8 <- unique(s8)
s9 <- unique(s9)
s10 <- unique(s10)
s11 <- unique(s11)
s12 <- unique(s12)
s13 <- unique(s13)
s14 <- unique(s14)
s15 <- unique(s15)
s16 <- unique(s16)
s17 <- unique(s17)
s18 <- unique(s18)
s19 <- unique(s19)



clin$PIK3CB <- ifelse(clin$Tumor_Sample_Barcode %in% s1$Tumor_Sample_Barcode, "1", "0")
clin$TOP2A <- ifelse(clin$Tumor_Sample_Barcode %in% s2$Tumor_Sample_Barcode, "1", "0")
clin$NTRK1 <- ifelse(clin$Tumor_Sample_Barcode %in% s3$Tumor_Sample_Barcode, "1", "0")
clin$ZNRF3 <- ifelse(clin$Tumor_Sample_Barcode %in% s4$Tumor_Sample_Barcode, "1", "0")
clin$ARID1A <- ifelse(clin$Tumor_Sample_Barcode %in% s5$Tumor_Sample_Barcode, "1", "0")
clin$ERBB3 <- ifelse(clin$Tumor_Sample_Barcode %in% s6$Tumor_Sample_Barcode, "1", "0")
clin$NOTCH3 <- ifelse(clin$Tumor_Sample_Barcode %in% s7$Tumor_Sample_Barcode, "1", "0")
clin$MSH6 <- ifelse(clin$Tumor_Sample_Barcode %in% s8$Tumor_Sample_Barcode, "1", "0")
clin$PDGFRB <- ifelse(clin$Tumor_Sample_Barcode %in% s9$Tumor_Sample_Barcode, "1", "0")
clin$EPHB4 <- ifelse(clin$Tumor_Sample_Barcode %in% s10$Tumor_Sample_Barcode, "1", "0")
clin$ASH1L <- ifelse(clin$Tumor_Sample_Barcode %in% s11$Tumor_Sample_Barcode, "1", "0")
clin$EZH2 <- ifelse(clin$Tumor_Sample_Barcode %in% s12$Tumor_Sample_Barcode, "1", "0")
clin$MTOR <- ifelse(clin$Tumor_Sample_Barcode %in% s13$Tumor_Sample_Barcode, "1", "0")
clin$AR <- ifelse(clin$Tumor_Sample_Barcode %in% s14$Tumor_Sample_Barcode, "1", "0")
clin$ETV6 <- ifelse(clin$Tumor_Sample_Barcode %in% s15$Tumor_Sample_Barcode, "1", "0")
clin$SEC63 <- ifelse(clin$Tumor_Sample_Barcode %in% s16$Tumor_Sample_Barcode, "1", "0")
clin$CEBPZ <- ifelse(clin$Tumor_Sample_Barcode %in% s17$Tumor_Sample_Barcode, "1", "0")
clin$PTCH2 <- ifelse(clin$Tumor_Sample_Barcode %in% s18$Tumor_Sample_Barcode, "1", "0")
clin$BRCA2 <- ifelse(clin$Tumor_Sample_Barcode %in% s19$Tumor_Sample_Barcode, "1", "0")


##Co-occurrence
s20 <- maf %>% filter(Hugo_Symbol == "ASXL1") %>% select(Tumor_Sample_Barcode)
s21 <- maf %>% filter(Hugo_Symbol == "POLE") %>% select(Tumor_Sample_Barcode)
s22 <- maf %>% filter(Hugo_Symbol == "FBXW7") %>% select(Tumor_Sample_Barcode)
s23 <- maf %>% filter(Hugo_Symbol == "PTEN") %>% select(Tumor_Sample_Barcode)
s24 <- maf %>% filter(Hugo_Symbol == "BRCA1") %>% select(Tumor_Sample_Barcode)
s25 <- maf %>% filter(Hugo_Symbol == "ROS1") %>% select(Tumor_Sample_Barcode)
s26 <- maf %>% filter(Hugo_Symbol == "BRAF") %>% select(Tumor_Sample_Barcode)
s27 <- maf %>% filter(Hugo_Symbol == "BARD1") %>% select(Tumor_Sample_Barcode)
s28 <- maf %>% filter(Hugo_Symbol == "RNF43") %>% select(Tumor_Sample_Barcode)

s20 <- unique(s20)
s21 <- unique(s21)
s22 <- unique(s22)
s23 <- unique(s23)
s24 <- unique(s24)
s25 <- unique(s25)
s26 <- unique(s26)
s27 <- unique(s27)
s28 <- unique(s28)

clin$ASXL1 <- ifelse(clin$Tumor_Sample_Barcode %in% s20$Tumor_Sample_Barcode, "1", "0")
clin$POLE <- ifelse(clin$Tumor_Sample_Barcode %in% s21$Tumor_Sample_Barcode, "1", "0")
clin$FBXW7 <- ifelse(clin$Tumor_Sample_Barcode %in% s22$Tumor_Sample_Barcode, "1", "0")
clin$PTEN <- ifelse(clin$Tumor_Sample_Barcode %in% s23$Tumor_Sample_Barcode, "1", "0")
clin$BRCA1 <- ifelse(clin$Tumor_Sample_Barcode %in% s24$Tumor_Sample_Barcode, "1", "0")
clin$ROS1 <- ifelse(clin$Tumor_Sample_Barcode %in% s25$Tumor_Sample_Barcode, "1", "0")
clin$BRAF <- ifelse(clin$Tumor_Sample_Barcode %in% s26$Tumor_Sample_Barcode, "1", "0")
clin$BARD1 <- ifelse(clin$Tumor_Sample_Barcode %in% s27$Tumor_Sample_Barcode, "1", "0")
clin$RNF43 <- ifelse(clin$Tumor_Sample_Barcode %in% s28$Tumor_Sample_Barcode, "1", "0")

clin$NTRK1_ASXL1 <- ifelse(clin$NTRK1 == "1", ifelse(clin$ASXL1 == "1", "1", "0"), "0")
clin$TOP2A_ASXL1 <- ifelse(clin$TOP2A == "1", ifelse(clin$ASXL1 == "1", "1", "0"), "0")
clin$PDGFRB_EPHB4 <- ifelse(clin$PDGFRB == "1", ifelse(clin$EPHB4 == "1", "1", "0"), "0")
clin$MTOR_MSH6 <- ifelse(clin$MTOR == "1", ifelse(clin$MSH6 == "1", "1", "0"), "0")
clin$TOP2A_NTRK1 <- ifelse(clin$TOP2A == "1", ifelse(clin$NTRK1 == "1", "1", "0"), "0")
clin$TOP2A_POLE <- ifelse(clin$TOP2A == "1", ifelse(clin$POLE == "1", "1", "0"), "0")
clin$NTRK1_FBXW7 <- ifelse(clin$NTRK1 == "1", ifelse(clin$FBXW7 == "1", "1", "0"), "0")
clin$TOP2A_FBXW7 <- ifelse(clin$TOP2A == "1", ifelse(clin$FBXW7 == "1", "1", "0"), "0")
clin$EPHB4_ARID1A <- ifelse(clin$EPHB4 == "1", ifelse(clin$ARID1A == "1", "1", "0"), "0")
clin$POLE_ASXL1 <- ifelse(clin$POLE == "1", ifelse(clin$ASXL1 == "1", "1", "0"), "0")
clin$ASXL1_FBXW7 <- ifelse(clin$ASXL1 == "1", ifelse(clin$FBXW7 == "1", "1", "0"), "0")
clin$ASXL1_ARID1A <- ifelse(clin$ASXL1 == "1", ifelse(clin$ARID1A == "1", "1", "0"), "0")
clin$PTEN_BRCA1 <- ifelse(clin$PTEN == "1", ifelse(clin$BRCA1 == "1", "1", "0"), "0")
clin$ROS1_BRCA1 <- ifelse(clin$ROS1 == "1", ifelse(clin$BRCA1 == "1", "1", "0"), "0")
clin$ARID1A_TOP2A <- ifelse(clin$ARID1A == "1", ifelse(clin$TOP2A == "1", "1", "0"), "0")
clin$ARID1A_NTRK1 <- ifelse(clin$ARID1A == "1", ifelse(clin$NTRK1 == "1", "1", "0"), "0")
clin$ARID1A_PDGFRB <- ifelse(clin$ARID1A == "1", ifelse(clin$PDGFRB == "1", "1", "0"), "0")
clin$BRAF_BARD1 <- ifelse(clin$BRAF == "1", ifelse(clin$BARD1 == "1", "1", "0"), "0")
clin$ARID1A_POLE <- ifelse(clin$ARID1A == "1", ifelse(clin$POLE == "1", "1", "0"), "0")
clin$ARID1A_RNF43 <- ifelse(clin$ARID1A == "1", ifelse(clin$RNF43 == "1", "1", "0"), "0")
clin$ARID1A_BRCA2 <- ifelse(clin$ARID1A == "1", ifelse(clin$BRCA2 == "1", "1", "0"), "0")
clin$BRCA2_TOP2A <- ifelse(clin$BRCA2 == "1", ifelse(clin$TOP2A == "1", "1", "0"), "0")



#write.xlsx(clin, paste0('./clin_data/', "clin.final.210405.xlsx"))


library(dplyr)
##Gene
s1 <- maf %>% filter(Hugo_Symbol == "BRCA1") %>% distinct(Tumor_Sample_Barcode)
s2 <- maf %>% filter(Hugo_Symbol == "BRCA2") %>% distinct(Tumor_Sample_Barcode)
s3 <- maf %>% filter(Hugo_Symbol == "BARD1") %>% distinct(Tumor_Sample_Barcode)
s4 <- maf %>% filter(Hugo_Symbol == "RNF43") %>% distinct(Tumor_Sample_Barcode)
s5 <- maf %>% filter(Hugo_Symbol == "CREBBP") %>% distinct(Tumor_Sample_Barcode)
s6 <- maf %>% filter(Hugo_Symbol == "BRAF") %>% distinct(Tumor_Sample_Barcode)
s7 <- maf %>% filter(Hugo_Symbol == "GNAS") %>% distinct(Tumor_Sample_Barcode)
s8 <- maf %>% filter(Hugo_Symbol == "NF1") %>% distinct(Tumor_Sample_Barcode)
s9 <- maf %>% filter(Hugo_Symbol == "ATM") %>% distinct(Tumor_Sample_Barcode)
s10 <- maf %>% filter(Hugo_Symbol == "ROS1") %>% distinct(Tumor_Sample_Barcode)
s11 <- maf %>% filter(Hugo_Symbol == "ASXL1") %>% distinct(Tumor_Sample_Barcode)
s12 <- maf %>% filter(Hugo_Symbol == "PTEN") %>% distinct(Tumor_Sample_Barcode)
s13 <- maf %>% filter(Hugo_Symbol == "KRAS") %>% distinct(Tumor_Sample_Barcode)
s14 <- maf %>% filter(Hugo_Symbol == "SMAD4") %>% distinct(Tumor_Sample_Barcode)
s15 <- maf %>% filter(Hugo_Symbol == "PIK3CA") %>% distinct(Tumor_Sample_Barcode)
s16 <- maf %>% filter(Hugo_Symbol == "ARID1A") %>% distinct(Tumor_Sample_Barcode)
s17 <- maf %>% filter(Hugo_Symbol == "FBXW7") %>% distinct(Tumor_Sample_Barcode)
s18 <- maf %>% filter(Hugo_Symbol == "MTOR") %>% distinct(Tumor_Sample_Barcode)
s19 <- maf %>% filter(Hugo_Symbol == "EPHB4") %>% distinct(Tumor_Sample_Barcode)
s20 <- maf %>% filter(Hugo_Symbol == "MSH6") %>% distinct(Tumor_Sample_Barcode)
s21 <- maf %>% filter(Hugo_Symbol == "PDGFRB") %>% distinct(Tumor_Sample_Barcode)

s1 <- unique(s1)
s2 <- unique(s2)
s3 <- unique(s3)
s4 <- unique(s4)
s5 <- unique(s5)
s6 <- unique(s6)
s7 <- unique(s7)
s8 <- unique(s8)
s9 <- unique(s9)
s10 <- unique(s10)
s11 <- unique(s11)
s12 <- unique(s12)
s13 <- unique(s13)
s14 <- unique(s14)
s15 <- unique(s15)
s16 <- unique(s16)
s17 <- unique(s17)
s18 <- unique(s18)
s19 <- unique(s19)
s20 <- unique(s20)
s21 <- unique(s21)



clin$BRCA1 <- ifelse(clin$Tumor_Sample_Barcode %in% s1$Tumor_Sample_Barcode, "1", "0")
clin$BRCA2 <- ifelse(clin$Tumor_Sample_Barcode %in% s2$Tumor_Sample_Barcode, "1", "0")
clin$BARD1 <- ifelse(clin$Tumor_Sample_Barcode %in% s3$Tumor_Sample_Barcode, "1", "0")
clin$RNF43 <- ifelse(clin$Tumor_Sample_Barcode %in% s4$Tumor_Sample_Barcode, "1", "0")
clin$CREBBP <- ifelse(clin$Tumor_Sample_Barcode %in% s5$Tumor_Sample_Barcode, "1", "0")
clin$BRAF <- ifelse(clin$Tumor_Sample_Barcode %in% s6$Tumor_Sample_Barcode, "1", "0")
clin$GNAS <- ifelse(clin$Tumor_Sample_Barcode %in% s7$Tumor_Sample_Barcode, "1", "0")
clin$NF1 <- ifelse(clin$Tumor_Sample_Barcode %in% s8$Tumor_Sample_Barcode, "1", "0")
clin$ATM <- ifelse(clin$Tumor_Sample_Barcode %in% s9$Tumor_Sample_Barcode, "1", "0")
clin$ROS1 <- ifelse(clin$Tumor_Sample_Barcode %in% s10$Tumor_Sample_Barcode, "1", "0")
clin$ASXL1 <- ifelse(clin$Tumor_Sample_Barcode %in% s12$Tumor_Sample_Barcode, "1", "0")
clin$PTEN <- ifelse(clin$Tumor_Sample_Barcode %in% s13$Tumor_Sample_Barcode, "1", "0")
clin$KRAS <- ifelse(clin$Tumor_Sample_Barcode %in% s14$Tumor_Sample_Barcode, "1", "0")
clin$SMAD4 <- ifelse(clin$Tumor_Sample_Barcode %in% s15$Tumor_Sample_Barcode, "1", "0")
clin$ARID1A <- ifelse(clin$Tumor_Sample_Barcode %in% s16$Tumor_Sample_Barcode, "1", "0")
clin$FBXW7 <- ifelse(clin$Tumor_Sample_Barcode %in% s17$Tumor_Sample_Barcode, "1", "0")
clin$MTOR <- ifelse(clin$Tumor_Sample_Barcode %in% s18$Tumor_Sample_Barcode, "1", "0")
clin$EPHB4 <- ifelse(clin$Tumor_Sample_Barcode %in% s19$Tumor_Sample_Barcode, "1", "0")
clin$MSH6 <- ifelse(clin$Tumor_Sample_Barcode %in% s20$Tumor_Sample_Barcode, "1", "0")
clin$PDGFRB <- ifelse(clin$Tumor_Sample_Barcode %in% s21$Tumor_Sample_Barcode, "1", "0")



clin <- clin %>% mutate(BRCA1_BRCA2 = ifelse(clin$BRCA1 == "0", ifelse(clin$BRCA2 == "0", "0", "1"), ifelse(clin$BRCA2 == "0", "1", "1")))
clin <- clin %>% mutate(BARD1_BRCA2 = ifelse(clin$BARD1 == "0", ifelse(clin$BRCA2 == "0", "0", "1"), ifelse(clin$BRCA2 == "0", "1", "1")))
clin <- clin %>% mutate(RNF43_CREBBP = ifelse(clin$RNF43 == "0", ifelse(clin$CREBBP == "0", "0", "1"), ifelse(clin$CREBBP == "0", "1", "1")))
clin <- clin %>% mutate(BARD1_BRCA1 = ifelse(clin$BARD1 == "0", ifelse(clin$BRCA1 == "0", "0", "1"), ifelse(clin$BRCA1 == "0", "1", "1")))
clin <- clin %>% mutate(RNF43_BRAF = ifelse(clin$RNF43 == "0", ifelse(clin$BRAF == "0", "0", "1"), ifelse(clin$BRAF == "0", "1", "1")))
clin <- clin %>% mutate(BRCA1_GNAS = ifelse(clin$BRCA1 == "0", ifelse(clin$GNAS == "0", "0", "1"), ifelse(clin$GNAS == "0", "1", "1")))
clin <- clin %>% mutate(RNF43_NF1 = ifelse(clin$RNF43 == "0", ifelse(clin$NF1 == "0", "0", "1"), ifelse(clin$NF1 == "0", "1", "1")))
clin <- clin %>% mutate(GNAS_BRCA2 = ifelse(clin$GNAS == "0", ifelse(clin$BRCA2 == "0", "0", "1"), ifelse(clin$BRCA2 == "0", "1", "1")))
clin <- clin %>% mutate(BRCA1_ATM = ifelse(clin$BRCA1 == "0", ifelse(clin$ATM == "0", "0", "1"), ifelse(clin$ATM == "0", "1", "1")))
clin <- clin %>% mutate(ROS1_ATM = ifelse(clin$ROS1 == "0", ifelse(clin$ATM == "0", "0", "1"), ifelse(clin$ATM == "0", "1", "1")))
clin <- clin %>% mutate(ASXL1_BRAF = ifelse(clin$ASXL1 == "0", ifelse(clin$BRAF == "0", "0", "1"), ifelse(clin$BRAF == "0", "1", "1")))
clin <- clin %>% mutate(PTEN_RNF43 = ifelse(clin$PTEN == "0", ifelse(clin$RNF43 == "0", "0", "1"), ifelse(clin$RNF43 == "0", "1", "1")))
clin <- clin %>% mutate(ROS1_RNF43 = ifelse(clin$ROS1 == "0", ifelse(clin$RNF43 == "0", "0", "1"), ifelse(clin$RNF43 == "0", "1", "1")))
clin <- clin %>% mutate(CREBBP_BRCA2 = ifelse(clin$CREBBP == "0", ifelse(clin$BRCA2 == "0", "0", "1"), ifelse(clin$BRCA2 == "0", "1", "1")))
clin <- clin %>% mutate(RNF43_ATM = ifelse(clin$RNF43 == "0", ifelse(clin$ATM == "0", "0", "1"), ifelse(clin$ATM == "0", "1", "1")))
clin <- clin %>% mutate(KRAS_SMAD4 = ifelse(clin$KRAS == "0", ifelse(clin$SMAD4 == "0", "0", "1"), ifelse(clin$SMAD4 == "0", "1", "1")))
clin <- clin %>% mutate(BRCA2_PIK3CA = ifelse(clin$BRCA2 == "0", ifelse(clin$PIK3CA == "0", "0", "1"), ifelse(clin$PIK3CA == "0", "1", "1")))
clin <- clin %>% mutate(ARID1A_CREBBP = ifelse(clin$ARID1A == "0", ifelse(clin$CREBBP == "0", "0", "1"), ifelse(clin$CREBBP == "0", "1", "1")))
clin <- clin %>% mutate(NF1_FBXW7 = ifelse(clin$NF1 == "0", ifelse(clin$FBXW7 == "0", "0", "1"), ifelse(clin$FBXW7 == "0", "1", "1")))
clin <- clin %>% mutate(EPHB4_MTOR = ifelse(clin$EPHB4 == "0", ifelse(clin$MTOR == "0", "0", "1"), ifelse(clin$MTOR == "0", "1", "1")))
clin <- clin %>% mutate(BRCA1_ARID1A = ifelse(clin$BRCA1 == "0", ifelse(clin$ARID1A == "0", "0", "1"), ifelse(clin$ARID1A == "0", "1", "1")))
clin <- clin %>% mutate(NF1_BRAF = ifelse(clin$NF1 == "0", ifelse(clin$BRAF == "0", "0", "1"), ifelse(clin$BRAF == "0", "1", "1")))
clin <- clin %>% mutate(CREBBP_MSH6 = ifelse(clin$CREBBP == "0", ifelse(clin$MSH6 == "0", "0", "1"), ifelse(clin$MSH6 == "0", "1", "1")))
clin <- clin %>% mutate(ROS1_MSH6 = ifelse(clin$ROS1 == "0", ifelse(clin$MSH6 == "0", "0", "1"), ifelse(clin$MSH6 == "0", "1", "1")))
clin <- clin %>% mutate(ROS1_PDGFRB = ifelse(clin$ROS1 == "0", ifelse(clin$PDGFRB == "0", "0", "1"), ifelse(clin$PDGFRB == "0", "1", "1")))

#write.xlsx(clin, "clin_cnv.210409.xlsx")

